### PR TITLE
Remove dead link

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by brianhlin** [comment]
@rynge is there a new location for this document?

**Comment by rynge** [comment]
Hold on - I think that was removed by mistake.

**Comment by matyasselmeci** [comment]
OK, if that page gets restored then feel free to close this PR.

**Comment by brianhlin** [comment]
Ultimately we want to actually move that doc to https://opensciencegrid.org/docs/ (we'll try to tackle it in the upcoming doc focus) so the link should point to the new doc.

**Pull request closed without merging**
