### PR TITLE
Have S&R do most of the old release removal

### PR DESCRIPTION
**Pull request by matyasselmeci**
As requested by Scott Teige, deletion and mash configuration should be done by
the Software & Release team instead of Operations. S&R should still coordinate
with Ops for permission and timing.

### CODE REVIEW

**Comment by brianhlin** [comment]
@steige2 Why is maintenance of the repo machines at IU an S&R task?

**Comment by matyasselmeci** [comment]
Scott expressed this as a preference, not a requirement, and others have rejected it. Closing.

**Comment by steige2** [comment]
Added one step to the process.
S

Scott Teige PhD
Grid Operations Center Manager
Indiana University Research Technologies
steige@iu.edu<mailto:steige@iu.edu>
Office: +1 812 856 7331




On Oct 19, 2017, at 3:32 PM, Matyas Selmeci <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #330<https://github.com/opensciencegrid/technology/pull/330>.

**Comment by matyasselmeci** [comment]
What's the step? Where did you put it?

**Comment by steige2** [comment]
First line under S&R responsibilities.
Says "S&R shall enumerate the directories to be deleted”
S

Scott Teige PhD
Grid Operations Center Manager
Indiana University Research Technologies
steige@iu.edu<mailto:steige@iu.edu>
Office: +1 812 856 7331




On Oct 20, 2017, at 10:31 AM, Matyas Selmeci <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the step? Where did you put it?

**Pull request closed without merging**
