### PR TITLE
explicitly set theme: palette: scheme to default (light theme)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by brianhlin** [comment]
Does this mean that it worked for you locally?

**Comment by edquist** [comment]
Nope!

I was hoping to look at it deployed in the technology repo to verify, since in any case that will have a lesser impact on our users.

**Comment by edquist** [comment]
Built locally, doesn't seem to change anything for me.

**Comment by brianhlin** [comment]
Capturing the Slack discussion: this requires `mkdocs-material 5.2.0`, which requires `mkdocs 1.1` and Python 3, but we can't move off of Python 3 until we replace the `linkchecker`: https://opensciencegrid.atlassian.net/browse/SOFTWARE-3759

**Comment by edquist** [comment]
It might also be that once we upgrade mkdocs, the default theme will behave properly without this change.

**Comment by brianhlin** [comment]
Fixed by #851, closing

**Pull request closed without merging**
