### PR TITLE
Widen the content when the window is large enough

### PR DESCRIPTION
**Pull request by brianhlin**
Stole the CSS from [here](https://github.com/squidfunk/mkdocs-material/issues/619#issuecomment-348610715)

### CODE REVIEW

**Comment by osg-cat** [comment]
I don’t really have any comments, at least without digging way into the HTML and CSS. Does it seem to work? How many platforms and browsers have you tested? How many screen widths?

**Comment by djw8605** [comment]
@brianhlin could you deploy this on the ITB site?

**Comment by brianhlin** [comment]
@djw8605 we don't have a technology ITB site but I could set one up once I remember how to do that

**Comment by brianhlin** [comment]
https://opensciencegrid.github.io/technology-itb/

**Comment by brianhlin** [comment]
I actually think it looks kinda bad the more I look at it. Using the entirety of a wide screen makes it really annoying to read paragraphs. Pushing new commits to the ITB.

**Comment by brianhlin** [comment]
And even just slightly wider looks worse, too, imo. It makes text more difficult to read but tables definitely look better.

I'm inclined to abandon these changes (but cherry pick the ITB and robots updates)

**Pull request closed without merging**
