### PR TITLE
Add link checking and strict building

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
@matyasselmeci well this takes forever now and is impossibly verbose. We should probably control the output and suppress warnings and whatnot. Maybe we can also:

1. Ignore all the Tech area notes
2. Only inspect links for new/recently touched files? Is there a way we can only inspect links for files that were just modified in the PR? I'm imagining some hackery with comparing the branch against `master` and getting a list of changed files.

**Comment by matyasselmeci** [comment]
Once you think it's ready, you should squash some of those commits...

**Comment by brianhlin** [comment]
Oh, trust me, I know :)

**Comment by brianhlin** [comment]
Ugh, the version of linkchecker available in Ubuntu Trusty has broken warning suppression: https://github.com/wummel/linkchecker/pull/457

**Comment by brianhlin** [comment]
Squashed the grotesque sausage-making process

**Pull request merged**
