### PR TITLE
Document how to verify builds via Travis-CI

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
This isn't actually going to work unless they have all their BuildRequires already installed in the container.

**Comment by brianhlin** [comment]
Does Koji handle that for us for our scratch/real builds?

**Comment by matyasselmeci** [comment]
Mock handles it, therefore Koji handles it.

**Comment by brianhlin** [comment]
@matyasselmeci this should be ready to go now

**Comment by matyasselmeci** [comment]
Did you try it? Did it work?

**Comment by brianhlin** [comment]
yes on both counts: https://travis-ci.org/opensciencegrid/xcache/builds/547382581?utm_source=github_status&utm_medium=notification

**Pull request merged**
