### PR TITLE
Update RPM Development Guide with new OSG-Build features

### PR DESCRIPTION
**Pull request by matyasselmeci**
SOFTWARE-3119, SOFTWARE-3171, SOFTWARE-3156

### CODE REVIEW

**Comment by efajardo** [comment]
I disagree with @brianhlin if that version number would not have been in the documentation I would have spent who knows how many hours trying to debug the problem. Since the error it spits when running an older version and trying to do github rpm is not clear at all. In this case, I am in favor of keeping in since which version a new feature is supported.

**Comment by brianhlin** [comment]
Our documentation is generally written with the assumption that users are running the latest OSG packages. The alternative is writing up a policy for when and for how long version numbers should be referenced and we already have enough trouble cleaning up old documentation as it is that I don't think it's feasible.

**Comment by matyasselmeci** [comment]
Where do we document that assumption?

**Comment by brianhlin** [comment]
I don't think we do for the general case. Maybe we should but I'm not sure where/how we could do it without being lost. Maybe we start a general troubleshooting page? I'm not yet convinced we need such documentation, though.

**Comment by brianhlin** [comment]
@efajardo I'd also like to point out that troubleshooting this should not take hours because the first thing you (and our users) should have done is check that you're using the latest packages.

**Comment by DrDaveD** [comment]
At least some OSG documentation pages have an "applicable versions" (e.g. [install-cvmfs](https://opensciencegrid.github.io/docs/other/install-cvmfs-stratum1/)) at the top.  I think that's the easiest way to handle different versions.  I don't think it should be scattered throughout a page, with different features appearing in different versions.

**Comment by brianhlin** [comment]
@timtheisen this was missed during the release

**Pull request merged**
