### PR TITLE
Updated container development guide

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I added a section on using the new images repo but I kept the section on the old one-image-per-repo style repos since we still have a bunch of those lying around that we'll need to keep updated.

(Also TBH while I like the images repo, we seem to be pushing against GitHub limitations with our large number of tasks per action...)

I could use some help with reviewing the mechanisms (the "Triggering Container Image Builds" section mostly) - do those still apply to the images repo?

**Comment by brianhlin** [comment]
> I could use some help with reviewing the mechanisms (the "Triggering Container Image Builds" section mostly) - do those still apply to the images repo?

The directions are slightly off, you have to choose a specific workflow after you go to the actions tab, then you get the drop down to kick off a workflow dispatch. You should have permission to kick off a manual rebuild here: https://github.com/opensciencegrid/images/actions/workflows/build-containers.yml

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by brianhlin** [comment]
Just gonna get this merged since it's blocking @CannonLock on making the transfer to osg-htc

**Pull request merged**
